### ISSUE TITLE
On_message handler running twice on some functions

### ISSUE THREAD

**Issue by Eikosa** [hydrogram/hydrogram#31]
### Checklist

- [X] I am sure the error is coming from Hydrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/hydrogram/hydrogram/archive/dev.zip` and reproduced the issue using the latest development version

### Description

When I run it in pyrogram, the handler works only once and gives the desired result, but when I change all pyrogram text in my code to hydrogram and run my code again, I observe that *only some* functions are working twice even though I send a single command, I can't figure out the reason for this.

### Steps to reproduce

I can't send it because my bot is huge, but I can say that I have many handlers, groups and plugins. Also, when I run the exact same code in windows it works once, but when I run it in ubuntu 22.04 it works twice, I think this problem is also related to the operating system.

### Code example

```python
@app.on_message(filters.command(['start']))
async def start(client, message):
    chat_id = message.chat.id
    await client.send_message(chat_id, "Hi")
```

### Logs

```shell
Pyrogram:
User: /start
Bot: Hi

Hydrogram
User: /start
Bot: Hi
Bot: Hi
```

**Comment by alissonlauffer** [comment]
Hello, in my setup, I'm using https://t.me/EduuRobot with latest Hydrogram commit, without any issue like this one. However, I remember having such issues when my time was out-of-sync, which makes the library to retry sending queries and timeout sometimes.

Can you verify that your time is in sync with a NTP server? If you're under Linux, try running `sudo ntpdate pool.ntp.org`.

**Comment by Eikosa** [comment]
In my other bots, when I replaced all the pyrogram text to hydrogram, it worked fine, but unfortunately I encountered this problem when I did this in my most complex bot. And i synchronized it as you said, but it didn't fix it.

**Comment by alissonlauffer** [comment]
Hello, can you try the latest commit? It should probably fix your issue.
