### ISSUE TITLE
400 MESSAGE_NOT_MODIFIED

### ISSUE THREAD

**Issue by KSKOP69** [hydrogram/hydrogram#6]
### Checklist

- [X] I am sure the error is coming from Hydrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran pip3 install -U https://github.com/hydrogram/hydrogram/archive/dev.zip and reproduced the issue using the latest development version

### Description

hydrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage") 

### Steps to reproduce

1. installed hydrogram 
2. deployed the bot 
3. got the error

### Code example

return await CallbackQuery.edit_message_media(

### Logs

https://batbin.me/b15356182286487b8b7c49795bedff5e

**Comment by davitudoplugins1234** [comment]
@AnonymousX1025 The error also exists in the pyrogram, and it is very common both here and there

**Comment by davitudoplugins1234** [comment]
@davitudoplugins1234 Oxi

**Comment by AnonymousX1025** [comment]
> @AnonymousX1025 The error also exists in the pyrogram, and it is very common both here and there

🤡
